image: python:3.7

stages:
  - dockerize

dockerize:
  stage: dockerize
  only:
    - main
  image: docker:18.09
  tags:
    - "kelerp"
  #variables:
    #DOCKER_HOST: tcp://docker:2375/
  #services:
    #- docker:18.09-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST