image: python:3.7

variables:
  # Please edit to your GitLab project
  REPO_NAME: https://gitlab.com/kelerp/erpbackend.git
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  APP_PORT: 8000
  DOCKER_TLS_CERTDIR: ""
  FF_NETWORK_PER_BUILD: "true"


stages:
  - dockerize
  - deploy_stage

dockerize:
  stage: dockerize
  only:
    - main
  image: docker:18.09
  tags:
    - "kelerp"
  #variables:
    #DOCKER_HOST: tcp://docker:2375/
  #services:
    #- docker:18.09-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  
deploy_stage:
  stage: deploy_stage
  environment:
    name: staging
    url: $STAGE_URL/static/swagger-ui.html
  tags:
    - "chatbot02"
  only:
    - master
  image: docker:dind
  script:
    - echo "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA"
    - docker stop erpbackend_app:ctrl || true
    - docker rm -f erpbackend_app:ctrl || true
    - docker run -p 8000:8000 -d --name  erpbackend_app:ctrl $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA